// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3MPWklJmH7ulQTpqbKq3Db1sLRR_e1A',
    appId: '1:637701175257:web:58d9159105ad8313c24bc8',
    messagingSenderId: '637701175257',
    projectId: 'inmakes-11c75',
    authDomain: 'inmakes-11c75.firebaseapp.com',
    storageBucket: 'inmakes-11c75.firebasestorage.app',
    measurementId: 'G-QCLT52JYJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_6RypAKd0QXMX649dzwWorhFi74BPNk',
    appId: '1:637701175257:android:932538c7186304b8c24bc8',
    messagingSenderId: '637701175257',
    projectId: 'inmakes-11c75',
    storageBucket: 'inmakes-11c75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAcNXAYVfxSMt0Mt1sybZ3SZb1X3Yz2lE',
    appId: '1:637701175257:ios:8aa575052c51fb15c24bc8',
    messagingSenderId: '637701175257',
    projectId: 'inmakes-11c75',
    storageBucket: 'inmakes-11c75.firebasestorage.app',
    iosBundleId: 'com.example.inmakesBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAcNXAYVfxSMt0Mt1sybZ3SZb1X3Yz2lE',
    appId: '1:637701175257:ios:8aa575052c51fb15c24bc8',
    messagingSenderId: '637701175257',
    projectId: 'inmakes-11c75',
    storageBucket: 'inmakes-11c75.firebasestorage.app',
    iosBundleId: 'com.example.inmakesBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi3MPWklJmH7ulQTpqbKq3Db1sLRR_e1A',
    appId: '1:637701175257:web:b6270d1f09cefe6bc24bc8',
    messagingSenderId: '637701175257',
    projectId: 'inmakes-11c75',
    authDomain: 'inmakes-11c75.firebaseapp.com',
    storageBucket: 'inmakes-11c75.firebasestorage.app',
    measurementId: 'G-NPW0VQ2P86',
  );
}
